# Generated by Django 6.0.5 on 2026-05-28 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('asset_type', models.CharField(choices=[('CRYPTO', 'Crypto'), ('FOREX', 'Forex'), ('ETF', 'ETF'), ('INDEX', 'Index')], max_length=20)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('change_24h', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold')], max_length=10)),
                ('rationale', models.TextField(blank=True)),
                ('risk_level', models.CharField(default='Medium', max_length=30)),
                ('confidence', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='markets.marketasset')),
            ],
        ),
    ]
