# Generated by Django 6.0.5 on 2026-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='inactive', max_length=20)),
                ('plan_name', models.CharField(default='Weekly', max_length=80)),
                ('price', models.DecimalField(decimal_places=2, default=3.99, max_digits=6)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('provider', models.CharField(default='Carrier Billing', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
