# Generated by Django 6.0.5 on 2026-05-29 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_name', models.CharField(max_length=120)),
                ('headline', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('image_source', models.CharField(blank=True, max_length=255, null=True)),
                ('short_summary', models.TextField()),
                ('advanced_summary', models.TextField()),
                ('beginner_summary', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20)),
                ('news_type', models.CharField(choices=[('crypto', 'Crypto'), ('stock_market', 'Stock market'), ('forex', 'Forex'), ('investing_basics', 'Investing basics')], db_index=True, max_length=30)),
                ('importance_score', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('published_at', models.DateTimeField(db_index=True)),
                ('processed_at', models.DateTimeField()),
                ('original_language', models.CharField(max_length=10)),
                ('original_content', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('mentioned_assets', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['news_type', 'difficulty', 'status'], name='content_new_news_ty_01aeb3_idx')],
            },
        ),
    ]
