# Generated by Django 6.0.5 on 2026-06-02 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['quiz__lesson__course', 'quiz__lesson__order', 'order'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='lessonquizoption',
            name='unique_learning_quiz_option_order',
        ),
        migrations.RemoveConstraint(
            model_name='lessonquizoption',
            name='unique_learning_correct_option_per_quiz',
        ),
        migrations.AddField(
            model_name='course',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='is_required',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], db_index=True, default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_language',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('article', 'Article'), ('course', 'Course')], db_index=True, default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='embed_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='provider',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lesson',
            name='source_channel',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='lesson',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['language', 'is_active', 'order'], name='learning_co_languag_2a0603_idx'),
        ),
        migrations.AddField(
            model_name='lessonquizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.lessonquiz'),
        ),
        migrations.AddField(
            model_name='lessonquizoption',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning.lessonquizquestion'),
        ),
        migrations.AddConstraint(
            model_name='lessonquizoption',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', True)), fields=('quiz', 'order'), name='unique_learning_legacy_quiz_option_order'),
        ),
        migrations.AddConstraint(
            model_name='lessonquizoption',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('question', 'order'), name='unique_learning_question_option_order'),
        ),
        migrations.AddConstraint(
            model_name='lessonquizoption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True), ('question__isnull', True)), fields=('quiz',), name='unique_learning_legacy_correct_option_per_quiz'),
        ),
        migrations.AddConstraint(
            model_name='lessonquizoption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True), ('question__isnull', False)), fields=('question',), name='unique_learning_correct_option_per_question'),
        ),
        migrations.AddConstraint(
            model_name='lessonquizquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='unique_learning_quiz_question_order'),
        ),
    ]
