# Generated by Django 6.0.5 on 2026-06-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lessonquizquestion_and_more'),
        ('users', '0006_userprofile_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='selected_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_course_progress', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_lesson_progress', to='users.userprofile'),
        ),
    ]
