# Generated by Django 6.0.5 on 2026-06-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_userlessonprogress_selected_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_url',
            field=models.URLField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='provider',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='course',
            name='source_type',
            field=models.CharField(choices=[('institutional', 'Institutional'), ('university', 'University'), ('commercial_platform', 'Commercial platform'), ('independent_creator', 'Independent creator'), ('media', 'Media'), ('curated', 'Curated')], db_index=True, default='curated', max_length=40),
        ),
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='learning.learningcategory'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='disclaimer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='embed_allowed',
            field=models.CharField(choices=[('true', 'Allowed'), ('false', 'Not allowed'), ('manual_review', 'Manual review')], db_index=True, default='manual_review', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='external_url',
            field=models.URLField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='learning.learninglevel'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='requires_disclaimer',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='is_required',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='lessonquizquestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('true_false', 'True/false')], default='single_choice', max_length=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('article', 'Article'), ('course', 'Course'), ('podcast', 'Podcast'), ('tool', 'Tool'), ('glossary', 'Glossary')], db_index=True, default='video', max_length=20),
        ),
    ]
