# Generated by Django for marketdata initial schema.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialDataRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("SUCCESS", "Success"), ("PARTIAL_SUCCESS", "Partial success"), ("FAILED", "Failed")], default="PENDING", max_length=20)),
                ("provider", models.CharField(default="gemini", max_length=40)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("items_expected", models.PositiveIntegerField(default=0)),
                ("items_received", models.PositiveIntegerField(default=0)),
                ("items_imported", models.PositiveIntegerField(default=0)),
                ("items_skipped", models.PositiveIntegerField(default=0)),
                ("items_failed", models.PositiveIntegerField(default=0)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="FinancialProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(db_index=True, max_length=40, unique=True)),
                ("name_en", models.CharField(max_length=160)),
                ("name_pl", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("category", models.CharField(choices=[("CRYPTO", "Crypto"), ("INDEX", "Index"), ("FOREX", "Forex"), ("GENERAL", "General")], db_index=True, max_length=20)),
                ("subcategory", models.CharField(choices=[("COIN", "Coin"), ("STOCK_INDEX", "Stock index"), ("ETF", "ETF"), ("FX_PAIR", "FX pair"), ("METAL", "Metal"), ("COMMODITY", "Commodity"), ("MACRO", "Macro"), ("RATE", "Rate"), ("GDP", "GDP"), ("INFLATION", "Inflation"), ("UNEMPLOYMENT", "Unemployment"), ("HOUSING", "Housing"), ("BOND", "Bond"), ("RISK_PREMIUM", "Risk premium"), ("OTHER", "Other")], db_index=True, max_length=30)),
                ("unit", models.CharField(max_length=40)),
                ("unit_label_en", models.CharField(blank=True, max_length=120)),
                ("unit_label_pl", models.CharField(blank=True, max_length=120)),
                ("description_en", models.TextField(blank=True)),
                ("description_pl", models.TextField(blank=True)),
                ("default_detail_en", models.CharField(blank=True, max_length=160)),
                ("default_detail_pl", models.CharField(blank=True, max_length=160)),
                ("update_frequency", models.CharField(choices=[("DAILY", "Daily"), ("WEEKLY", "Weekly"), ("MONTHLY", "Monthly"), ("QUARTERLY", "Quarterly"), ("EVENT_BASED", "Event based"), ("UNKNOWN", "Unknown")], default="UNKNOWN", max_length=20)),
                ("data_granularity", models.CharField(choices=[("REALTIME", "Realtime"), ("DAILY_CLOSE", "Daily close"), ("MONTHLY", "Monthly"), ("QUARTERLY", "Quarterly"), ("EVENT", "Event"), ("UNKNOWN", "Unknown")], default="UNKNOWN", max_length=20)),
                ("display_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "symbol"],
                "indexes": [models.Index(fields=["category", "subcategory"], name="marketdata__categor_b62ab8_idx"), models.Index(fields=["is_active", "is_featured", "display_order"], name="marketdata__is_acti_9cfa98_idx")],
            },
        ),
        migrations.CreateModel(
            name="FinancialProductSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_value", models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ("previous_value", models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ("change_absolute", models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ("change_percent", models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ("effective_at_raw", models.CharField(blank=True, max_length=80, null=True)),
                ("previous_reference_at_raw", models.CharField(blank=True, max_length=80, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("previous_reference_date", models.DateField(blank=True, null=True)),
                ("effective_datetime", models.DateTimeField(blank=True, null=True)),
                ("previous_reference_datetime", models.DateTimeField(blank=True, null=True)),
                ("source_name", models.CharField(blank=True, max_length=160, null=True)),
                ("source_url", models.URLField(blank=True, max_length=500, null=True)),
                ("quality_note", models.TextField(blank=True, null=True)),
                ("confidence_score", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("raw_row", models.JSONField(blank=True, default=list)),
                ("validation_status", models.CharField(choices=[("VALID", "Valid"), ("PARTIAL", "Partial"), ("INVALID", "Invalid")], db_index=True, default="VALID", max_length=20)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="marketdata.financialproduct")),
                ("run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="snapshots", to="marketdata.financialdatarun")),
            ],
            options={
                "ordering": ["product__display_order", "-created_at"],
                "indexes": [models.Index(fields=["product", "-created_at"], name="marketdata__product_a14daf_idx"), models.Index(fields=["effective_date"], name="marketdata__effecti_61882f_idx"), models.Index(fields=["validation_status", "created_at"], name="marketdata__validat_cb79a0_idx")],
            },
        ),
    ]
