# Generated by Django 6.0.5 on 2026-07-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_run_items_updated_snapshot_dedup_constraint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='financialproductsnapshot',
            index=models.Index(fields=['product', 'validation_status', '-effective_date', '-effective_datetime', '-created_at'], name='market_snap_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='financialproductsnapshot',
            index=models.Index(fields=['product', '-effective_date', '-created_at'], name='market_snap_history_idx'),
        ),
    ]
