# Generated by Django 6.0.5 on 2026-07-09 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='integrator_sid',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='integrator_tid',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.CreateModel(
            name='SubscriptionEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tid', models.CharField(db_index=True, max_length=128)),
                ('sid', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('pending_registration', 'Pending registration'), ('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='pending_registration', max_length=32)),
                ('signup_token_hash', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('signup_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('access_until', models.DateField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('external_user_id', models.CharField(blank=True, max_length=128)),
                ('msisdn_hash', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('last_event_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_entitlement', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled')], db_index=True, max_length=32)),
                ('operator', models.CharField(blank=True, max_length=80)),
                ('integrator', models.CharField(blank=True, max_length=80)),
                ('service', models.CharField(blank=True, max_length=80)),
                ('tid', models.CharField(db_index=True, max_length=128)),
                ('sid', models.CharField(db_index=True, max_length=128)),
                ('occurred_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='processed', max_length=32)),
                ('action', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('entitlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.subscriptionentitlement')),
            ],
        ),
        migrations.AddIndex(
            model_name='subscriptionentitlement',
            index=models.Index(fields=['status', 'access_until'], name='users_subsc_status_8071a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionentitlement',
            constraint=models.UniqueConstraint(fields=('tid', 'sid'), name='unique_subscription_entitlement_tid_sid'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['tid', 'sid', 'occurred_at'], name='users_integ_tid_a548c2_idx'),
        ),
    ]
