# Generated by Django 6.1.1 on 2026-10-07 15:44

from django.db import migrations, models
from django.db.models import F


def mark_existing_registrations(apps, schema_editor):
    entitlement = apps.get_model('users', 'SubscriptionEntitlement')
    entitlement.objects.filter(
        user_id__isnull=False,
        registered_at__isnull=True,
    ).update(registered_at=F('updated_at'))


def remove_unverifiable_legacy_hashes(apps, schema_editor):
    entitlement = apps.get_model('users', 'SubscriptionEntitlement')
    event = apps.get_model('users', 'IntegrationEvent')

    # Historical values have no documented normalization or hashing contract.
    # Token signup remains available for these entitlements.
    entitlement.objects.exclude(msisdn_hash='').update(msisdn_hash='')

    sensitive_keys = {'msisdn', 'msisdn_hash', 'mobile', 'phone', 'phone_number'}
    for item in event.objects.iterator(chunk_size=500):
        payload = item.raw_payload
        if not isinstance(payload, dict):
            continue
        customer = payload.get('customer')
        if not isinstance(customer, dict):
            continue
        keys = [key for key in customer if key.lower() in sensitive_keys]
        if keys:
            for key in keys:
                customer.pop(key)
            item.raw_payload = payload
            item.save(update_fields=['raw_payload'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_integrator_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionentitlement',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionentitlement',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='msisdn_hash',
            field=models.CharField(blank=True, editable=False, max_length=67, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionentitlement',
            name='msisdn_hash',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.RunPython(mark_existing_registrations, migrations.RunPython.noop),
        migrations.RunPython(remove_unverifiable_legacy_hashes, migrations.RunPython.noop),
    ]
