# Generated by Django 6.1.1 on 2026-10-08 11:14

from django.db import migrations, models


def clear_active_expiry(apps, schema_editor):
    profile = apps.get_model('users', 'UserProfile')
    profile.objects.using(schema_editor.connection.alias).filter(
        estado='activo',
    ).update(fecha_renovacion=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscriptionentitlement_payment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fecha_renovacion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(clear_active_expiry, migrations.RunPython.noop),
    ]
